name: Playwright Tests
on: push

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Install Playwright Browsers
        run: pnpm exec playwright install --with-deps

      - name: Build app
        run: pnpm build:worker
        env:
          BASE_URL: http://localhost:8771
          SESSION_PASSWORD: ${{ secrets.SESSION_PASSWORD }}

      - name: Run Playwright tests
        run: pnpm exec playwright test
        env:
          BASE_URL: http://localhost:8771
          SESSION_PASSWORD: ${{ secrets.SESSION_PASSWORD }}

      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
